branch-defaults:
  master:
    environment: WorkerPlatform-api
global:
  application_name: WorkerPlatform-api
  branch: null
  default_ec2_keyname: turkey
  default_platform: Python 3.8
  default_region: ap-northeast-1
  include_git_submodules: true
  instance_profile: t3.micro
  platform_name: null
  platform_version: null
  repository: null
  sc: git
  workspace_type: Application
