# Generated by Django 3.2.7 on 2021-09-08 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_tel', models.CharField(max_length=8)),
                ('user_name', models.CharField(max_length=40, null=True)),
                ('user_year', models.IntegerField(null=True)),
                ('user_sex', models.BooleanField(null=True)),
                ('safecard_date', models.DateField(null=True)),
                ('regcard_date', models.DateField(null=True)),
                ('work_year', models.IntegerField(null=True)),
                ('lan_en', models.IntegerField(null=True)),
                ('lan_cantonese', models.IntegerField(null=True)),
                ('lan_mandarin', models.IntegerField(null=True)),
                ('user_pwd', models.CharField(max_length=8, null=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
            ],
        ),
    ]
