# Generated by Django 3.2.7 on 2021-09-16 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitList',
            fields=[
                ('benefit_id', models.AutoField(primary_key=True, serialize=False)),
                ('benefit_desc', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryList',
            fields=[
                ('salary_id', models.AutoField(primary_key=True, serialize=False)),
                ('salary_type', models.CharField(max_length=1)),
                ('salary_upper', models.IntegerField()),
                ('salary_lower', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='JobFavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jf_id', to='Api.jobinfo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uf_id', to='Api.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='JobApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('apply_comment', models.TextField(null=True)),
                ('apply_status', models.CharField(default='0', max_length=1)),
                ('pre_status', models.CharField(default='0', max_length=1)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ja_id', to='Api.jobinfo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ua_id', to='Api.userprofile')),
            ],
        ),
    ]
