# Generated by Django 3.2.7 on 2021-09-08 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_jobtypedetail_userjobtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userjobtype',
            name='jobtype_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobtypedesc', to='Api.jobtypedetail'),
        ),
        migrations.AlterField(
            model_name='userjobtype',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobtype', to='Api.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_sex',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
