# Generated by Django 3.2.7 on 2021-09-20 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_benefitlist_jobapply_jobfavor_salarylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='company_pwd',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
