# Generated by Django 3.2.7 on 2021-09-20 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_companyinfo_company_pwd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='company_pwd',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
