# Generated by Django 3.2.7 on 2021-09-20 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_courseinfo_coursetype_jobvacancyinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseinfo',
            old_name='cytpe_id',
            new_name='ctype_id',
        ),
    ]
