# Generated by Django 3.2.7 on 2021-09-21 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_rename_cytpe_id_courseinfo_ctype_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='start_date',
            field=models.TextField(default='待定'),
        ),
    ]
