# Generated by Django 3.2.7 on 2021-09-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0007_alter_courseinfo_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobvacancyinfo',
            name='match_num',
            field=models.IntegerField(default=0),
        ),
    ]
