# Generated by Django 3.2.7 on 2021-09-27 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Api', '0008_jobvacancyinfo_match_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_auth',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
