# Generated by Django 3.2.7 on 2021-09-28 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0010_alter_userprofile_user_auth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_pwd',
        ),
    ]
