# Generated by Django 3.2.7 on 2021-10-18 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Api', '0011_remove_userprofile_user_pwd'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='user_auth',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
