# Generated by Django 3.2.7 on 2021-11-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0013_auto_20211018_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsinfo',
            name='url_cover',
            field=models.ImageField(null=True, upload_to='news'),
        ),
    ]
