# Generated by Django 3.2.7 on 2021-11-29 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0015_auto_20211119_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapply',
            name='updated_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='url_cert',
            field=models.ImageField(null=True, upload_to='cert'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='url_logo',
            field=models.ImageField(null=True, upload_to='logo'),
        ),
        migrations.AlterField(
            model_name='newsinfo',
            name='url_cover',
            field=models.ImageField(null=True, upload_to='news'),
        ),
    ]
