# Generated by Django 3.2.7 on 2021-11-30 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0016_auto_20211129_0401'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyCodeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel_or_email', models.CharField(max_length=40)),
                ('verifycode', models.CharField(max_length=6)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
