# Generated by Django 3.2.7 on 2021-12-01 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0017_verifycodeinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycodeinfo',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
