# Generated by Django 3.2.7 on 2021-12-03 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0018_alter_verifycodeinfo_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='contact_tel',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='course_tel',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='searchinfo',
            name='contact_tel',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='traininginfo',
            name='training_tel',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_tel',
            field=models.CharField(max_length=13),
        ),
    ]
